# Generated by Django 3.1.3 on 2020-11-17 00:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.CharField(help_text='The format is one character and 2 to 9 digits', max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex=re.compile('[A-Z]\\d{2,9}'))])),
                ('Title', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=500)),
                ('Publisher', models.CharField(max_length=500)),
                ('PublishDate', models.DateField()),
                ('ISBN', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('BookInstanceID', models.CharField(help_text='the format is book id with a dot and 2 - 4 digits (i.e.: B001.01)', max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex=re.compile('[A-Z]\\d{2,9}[.]\\d{2,4}'))])),
                ('Status', models.CharField(choices=[('Maintenance', 'Maintenance'), ('On Loan', 'On Loan'), ('Available', 'Available')], default='a', max_length=15)),
                ('BookID', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.PROTECT, to='lms.book')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('ReserveID', models.AutoField(primary_key=True, serialize=False)),
                ('ReserveDate', models.DateField()),
                ('ReleaseDate', models.DateField(blank=True, null=True)),
                ('BookID', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.PROTECT, to='lms.book')),
                ('BookInstanceID', models.ForeignKey(blank=True, db_column='BookInstanceID', null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.bookinstance')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('BorrowID', models.AutoField(primary_key=True, serialize=False)),
                ('BorrowDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('ReturnDate', models.DateField(blank=True, null=True)),
                ('BookInstanceID', models.ForeignKey(db_column='BookInstanceID', on_delete=django.db.models.deletion.PROTECT, to='lms.bookinstance')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
