# Generated by Django 3.1.2 on 2020-11-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('Title', models.TextField()),
                ('Language', models.TextField()),
                ('Author', models.TextField()),
                ('Publisher', models.TextField()),
                ('PublishDate', models.DateField()),
                ('ISBN', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('BookInstanceID', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('Status', models.CharField(max_length=64)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.book')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('ReserveID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('ReserveDate', models.DateField()),
                ('ReleaseDate', models.DateField()),
                ('BookInstanceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.bookinstance')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('BorrowID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('BorrowDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('ReturnDate', models.DateField()),
                ('BookInstanceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.bookinstance')),
            ],
        ),
    ]
