# Generated by Django 3.1.2 on 2020-11-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='BookID',
            field=models.ForeignKey(db_column='Book_BookID', on_delete=django.db.models.deletion.PROTECT, to='lms.book'),
        ),
    ]
