# Generated by Django 3.1.3 on 2020-11-17 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='UserID',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='UserID',
            field=models.ForeignKey(db_column='UserID', default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='UserID',
            field=models.ForeignKey(db_column='UserID', default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
