# Generated by Django 3.1.3 on 2020-11-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20201117_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='UserID',
            new_name='Username',
        ),
    ]
