# Generated by Django 3.1.3 on 2020-11-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20201117_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='Username',
            new_name='UserID',
        ),
    ]
