# Generated by Django 3.1.2 on 2020-11-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20201116_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='BookID',
            field=models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.PROTECT, to='lms.book'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='BookInstanceID',
            field=models.ForeignKey(db_column='BookInstanceID', on_delete=django.db.models.deletion.PROTECT, to='lms.bookinstance'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='ReturnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='BookInstanceID',
            field=models.ForeignKey(db_column='BookInstanceID', on_delete=django.db.models.deletion.PROTECT, to='lms.bookinstance'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='ReleaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
