# Generated by Django 3.1.3 on 2020-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20201117_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
