# Generated by Django 3.1.2 on 2020-11-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20201116_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='BookID',
            field=models.ForeignKey(db_column='BookID', default='NULL', on_delete=django.db.models.deletion.PROTECT, to='lms.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='BookInstanceID',
            field=models.ForeignKey(blank=True, db_column='BookInstanceID', null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.bookinstance'),
        ),
    ]
